### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by zc994646659** [maituoy/BayesianOpt4dftu#10]
Can hse be used to optimize the cell, and will the result be good?  Setting the number of npad, kpar, and kpoints reasonably will affect the calculation speed of hse. Do you have any suggestions?

**Comment by zc994646659** [comment]
I have tried the optimization with hse,it may not succeed.So i do the non-self-consident calculation with the parameter provided. But the u_tmp.txt is only one. I see the  u_range is -10~10 in the example.py, what's wrong? and  how to go on the subsequent calculation?

**Comment by zc994646659** [comment]
[u_tmp.txt](https://github.com/maituoy/BayesianOpt4dftu/files/7453744/u_tmp.txt
[input.json.txt](https://github.com/maituoy/BayesianOpt4dftu/files/7453751/input.json.txt)
[example.py.txt](https://github.com/maituoy/BayesianOpt4dftu/files/7453752/example.py.txt)
)

**Comment by bailinyu** [comment]
> Can hse be used to optimize the cell, and will the result be good? Setting the number of npad, kpar, and kpoints reasonably will affect the calculation speed of hse. Do you have any suggestions?

Can I add you on QQ to discuss it，my QQ id is 276912810

**Comment by bailinyu** [comment]
Hello, I've seen your file. I want to know how to generate high symmetry points, when I generate high symmetry points using MS and SeekPath tool error
