### ISSUE TITLE
Some problems in learning Bayesian optimization

### ISSUE THREAD

**Issue by bailinyu** [maituoy/BayesianOpt4dftu#16]
Dear Yu,

I have successfully repeated 2D, and the results are consistent with those in your paper. But I still have some questions.
For example: 
1. Was the initial U value set randomly?
2. How do I generate high symmetry points and get errors when I generate high symmetry points using MS and SeekPath tools
Looking forward to your reply.

Happy New year!

Sincerely yours,
Bai Linyu

**Comment by maituoy** [comment]
For your questions:

1. The initial U value can be set in the `input.json` under pbe.
2. In the code, we generate the high symmetry k points using the `ase.dft.kpoints.get_special_points`. If the k points can not be found by ASE, I suggest you use the special_kpath.py in the source directory.

Hope that helps!
