### ISSUE TITLE
HSE calculation

### ISSUE THREAD

**Issue by Adllan** [maituoy/BayesianOpt4dftu#17]
The Hybrid function HSE just as reference (optional) of the Calculation or I must do it first (HSE)
I tray to remove hse flag form input.json and comment out hse in example.py after one iteration calculation stop and ask for ./hse/band/ (not found)
thank very much  for the very smart work

**Comment by maituoy** [comment]
HSE results is necessary for constructing the objective function but you only have to do it for the first time. After that, you can reuse the HSE results if you would like to adjust the hyperparameters or redo the optimization. To disable the HSE calculation, you just need to comment out the line `calculate(command=VASP_RUN_COMMAND, outfilename=OUTFILENAME, method='hse', import_kpath = import_kpath)` in your `example.py`.

**Comment by Adllan** [comment]
Thanks alot
