### ISSUE TITLE
question about import error

### ISSUE THREAD

**Issue by hfood02** [maituoy/BayesianOpt4dftu#18]
hello, I'm having some problems running example.py.
And the vaspvis have been installed(pip).
![image](https://user-images.githubusercontent.com/76612689/157473603-89f83099-b0fb-4ea3-8a77-2b754f248b1d.png)

**Comment by maituoy** [comment]
Hi, what version are you using? I think this has been fixed in the latest v0.1.4. Try `pip install BayesOpt4dftu --upgrade` and see if it solves the problem.

**Comment by hfood02** [comment]
Thanks a lot.  There are still some other errors after upgrade for it. I will check it again.
